version: '2'
services:
    esrsapplication-app:
        image: esrsapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://esrsapplication-postgresql:5432/ESRSApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    esrsapplication-postgresql:
        extends:
            file: postgresql.yml
            service: esrsapplication-postgresql
